### PR TITLE
Fix parsing on older versions of salt

### LINKED ISSUE #68: type assertion failure right after startup
Trying to run this against salt 2017.7.7 but I'm getting a type assertion failure right after startup. Not sure if this is due to old salt or what, hoping you can provide some insight? I can provide a fix assuming you're open to it but if this is a version thing then I'm sure there's probably more things like this to find too.

```
panic: interface conversion: interface {} is string, not []uint8

goroutine 9 [running]:
github.com/kpetremann/salt-exporter/pkg/parser.Event.Parse({_}, _)
	/home/runner/work/salt-exporter/salt-exporter/pkg/parser/parser.go:98 +0xa6c
github.com/kpetremann/salt-exporter/pkg/listener.(*EventListener).ListenEvents(0xc0000760f0)
	/home/runner/work/salt-exporter/salt-exporter/pkg/listener/listener.go:127 +0x16f
created by main.start in goroutine 1
	/home/runner/work/salt-exporter/salt-exporter/cmd/salt-exporter/main.go:72 +0x467
```

### PR DESCRIPTION
**Pull request by grimmy**
On older versions of salt, the message body is already a string which causes the .([]byte) type assertion to fail. This catches that failure than then tries an .(string) assertion to handle both cases.

Fixes #68

### CODE REVIEW

File: pkg/parser/parser.go [hunk 1]
```diff
@@ -95,7 +95,13 @@ func statemoduleResult(event event.SaltEvent) *bool {
 
 // ParseEvent parses a salt event.
 func (e Event) Parse(message map[string]interface{}) (event.SaltEvent, error) {
-	body := string(message["body"].([]byte))
+	var body string
+
+	if raw, ok := message["body"].([]byte); ok {
+		body = string(raw)
+	} else {
+		body = message["body"].(string)
```
Comment (kpetremann) [inline pkg/parser/parser.go:103]: could you please add a small comment to explain the reason of doing this fallback

File: pkg/parser/parser.go [hunk 2]
```diff
@@ -95,7 +95,13 @@ func statemoduleResult(event event.SaltEvent) *bool {
 
 // ParseEvent parses a salt event.
 func (e Event) Parse(message map[string]interface{}) (event.SaltEvent, error) {
-	body := string(message["body"].([]byte))
+	var body string
+
+	if raw, ok := message["body"].([]byte); ok {
```
Comment (kpetremann) [inline pkg/parser/parser.go:100]: using a type switch would be cleaner

**Comment by kpetremann** [comment]
hello,

I would have preferred to reproduce the issue first with Salt old version.
I am not sure whether the issue is coming from old Salt or old MsgPack.

**Comment by grimmy** [comment]
> hello,
> 
> Thanks for the PR :)

Of course!

> I would have preferred to reproduce the issue first with Salt old version. I am not sure whether the issue is coming from old Salt or old MsgPack. And I would like to make sure it won't break elsewhere for the old version.

I can reliably reproduce here as we have an old production server that we need to migrate from, but in the mean time I'm trying to add some monitoring before we do anything which led to me finding the issue.
